Repository rdkcentral/rdk-halif-test-rmf_audio_capture, pull requests merged in 2025-03, with the labels that each got.

#30 gh #29 Update hal_test_binary
  Makefile
  README.md
  bin/run.sh
  host/install.sh
Labels: enhancement

#37 issue35 l1 l2 nullhandlecheck
  src/test_l1_rmfAudioCapture.c
  src/test_l2_rmfAudioCapture.c
  src/test_l3_rmfAudioCapture.c
Labels: bug

#42 gh #41: support for step result dump
  host/tests/L1_L2_TestCases/rmfAudio_L1_L2_tests.py
  host/tests/rmfAudioClasses/rmfAudio.py
Labels: bug, enhancement
